export default {
	61888: "pixels",
	61872: "No error occurred.",
	61873: "An unknown error occurred while accessing %1.",
	61874: "An attempt was made to write to the reading %1.",
	61875: "An attempt was made to access %1 past its end.",
	61876: "An attempt was made to read from the writing %1.",
	61877: "%1 has a bad format.",
	61878: "%1 contained an unexpected object.",
	61879: "%1 contains an incorrect schema.",
	61856: "No error occurred.",
	61857: "An unknown error occurred while accessing %1.",
	61858: "%1 was not found.",
	61859: "%1 contains an invalid path.",
	61860: "%1 could not be opened because there are too many open files.",
	61861: "Access to %1 was denied.",
	61862: "An invalid file handle was associated with %1.",
	61863: "%1 could not be removed because it is the current directory.",
	61864: "%1 could not be created because the directory is full.",
	61865: "Seek failed on %1",
	61866: "A hardware I/O error was reported while accessing %1.",
	61867: "A sharing violation occurred while accessing %1.",
	61868: "A locking violation occurred while accessing %1.",
	61869: "Disk full while accessing %1.",
	61870: "An attempt was made to access %1 past its end.",
	61840: "Unable to load mail system support.",
	61841: "Mail system DLL is invalid.",
	61842: "Send Mail failed to send message.",
	61829: "%1\nUnable to register document.\nThe document may already be open.",
	61836: "Unable to read write-only property.",
	61837: "Unable to write read-only property.",
	61728: "Unexpected file format.",
	61729: "%1\nCannot find this file.\nPlease verify that the correct path and file name are given.",
	61730: "Destination disk drive is full.",
	61731: "Unable to read from %1, it is opened by someone else.",
	61732: "Unable to write to %1, it is read-only or opened by someone else.",
	61733: "An unexpected error occurred while reading %1.",
	61734: "An unexpected error occurred while writing %1.",
	61712: "Please enter an integer.",
	61713: "Please enter a number.",
	61714: "Please enter an integer between %1 and %2.",
	61715: "Please enter a number between %1 and %2.",
	61716: "Please enter no more than %1 characters.",
	61717: "Please select a button.",
	61718: "Please enter an integer between 0 and 255.",
	61719: "Please enter a positive integer.",
	61720: "Please enter a date and/or time.",
	61721: "Please enter a currency.",
	61696: "Invalid filename.",
	61697: "Failed to open document.",
	61698: "Failed to save document.",
	61699: "Save changes to %1?",
	61700: "Failed to create empty document.",
	61701: "The file is too large to open.",
	61702: "Could not start print job.",
	61703: "Failed to launch help.",
	61704: "Internal application error.",
	61705: "Command failed.",
	61706: "Insufficient memory to perform operation.",
	61707: "System registry entries have been removed and the INI file (if any) was deleted.",
	61708: "Not all of the system registry entries (or INI file) were removed.",
	61588: "Linked %s",
	61589: "Unknown Type",
	61472: "No error message is available.",
	61473: "An unsupported operation was attempted.",
	61474: "A required resource was unavailable.",
	61475: "Out of memory.",
	61476: "An unknown error has occurred.",
	61457: "&Hide",
	61440: "Open",
	61441: "Save As",
	61442: "All Files (*.*)",
	61443: "Untitled",
	61446: "an unnamed file",
	57392: "This JAWA is a friendly creature. It won't hurt you.",
	57393: "This is a friendly DROID. It won't hurt you.",
	57394: "C:\\Yoda",
	57395: "This is LUKE, Jedi-in-training...",
	57396: "This is an active TELEPORT STATION.\r\n\r\nStand on it, and if you have a LOCATOR, you can travel instantly to any other station on display. Just click and go!\r\n\r\nSometimes stations are helpfully placed, and sometimes not. Each world varies unpredictably.",
	57397: "This is a TELEPORT STATION.\r\n\r\nIt won't operate until you find a way to activate it.",
	57398: "This is a MEDICAL DROID. Visit him whenever you're seriously hurt, and he'll restore your health.",
	57400: "This is a WEAPON.  Pick it up!",
	57376: "This is a STORAGE DEVICE. There may be something valuable inside.\r\n\r\nIt may open when you bump it, or you may need a KEY CARD or TOOL. If an item appears, pick it up with a mouse CLICK on the FLASHING ICON.",
	57377: "This is your X-WING fighter.\r\n\r\nTo take off, bump into the cockpit.",
	57378: "Watch out! This is a dangerous ENEMY.\r\n\r\nTo defend yourself, you must ready a WEAPON. Select your lightsaber, a blaster or the Force from inventory with your mouse pointer, then click on Luke or the READY WEAPON DISPLAY.\r\n\r\nRemember, all weapons except the lightsaber gradually run out of power. Collect as many new ones as you can.",
	57379: "This is a DOOR.\r\n\r\nIt may open when you bump it, or you may need to use a KEY CARD or TOOL. Sometimes you need to make use of a nearby control panel.\r\n\r\nAnd don't worry... some doors never open.",
	57380: "You can PUSH and PULL this object.\r\n\r\nStand close beside it, hold down the SHIFT KEY, and start walking. Maybe you'll reveal a pathway, maybe you'll find something valuable, or maybe you'll just get some exercise.",
	57381: "This CHARACTER may be important to your mission.\r\n\r\nTo find out what's on his (or her, or its) mind, bump him, and he'll TALK to you.",
	57382: "This is YODA, Jedi Master.",
	57383: "I don't see anything special here, so let's talk about WALKING AROUND...\r\n\r\n...bleep... for fine control, position the mouse pointer at your destination and CLICK the left button.\r\n\r\nFor continuous travel, HOLD DOWN the left mouse button while you move the pointer.\r\n\r\nYou can also use the numeric KEY PAD with num lock off.\r\n\r\nTo go faster or slower, pull down the Options menu and adjust the GAME SPEED slider.",
	57384: "I don't see anything special here, so let's talk about FINDING THINGS...\r\n\r\n...zeeurrp... you need many ITEMS to win the game. Most of them are hidden!\r\n\r\nExplore every area of the world. Unlock doors and chests. Move obstacles aside.\r\n\r\nTo PICK UP an item, bump it and CLICK your left mouse button on the FLASHING ICON.",
	57385: "I don't see anything special here, so let's talk about USING THINGS...\r\n\r\n...whirrr... to USE an item, just select it from the inventory list with your mouse pointer and DROP the FLOATING ICON on something.\r\n\r\nFor example... to repair a speeder, CLICK on a likely PART ITEM, position the ICON over the vehicle, and CLICK again.\r\n\r\nBe sure to STAND CLOSE beside the object you're trying to affect. Except for the Force, actions don't work at a distance.\r\n\r\nIf  the first item you use doesn't produce results, try something else...",
	57386: "I don't see anything special here, so let's talk about JEDI WEAPONS...\r\n\r\n...nizzap... your LIGHTSABER and the FORCE have unusual powers. If nothing else works to solve a puzzle, try using them. Occasionally they'll surprise you!",
	57387: "I don't see anything special here, so let's talk about HEALTH...\r\n\r\n...boop beep... remember, the Star Wars Universe is a dangerous place. If your enemies seem too tough, pull down the Options menu and adjust the COMBAT DIFFICULTY slider.\r\n\r\nBe on the lookout for FOOD and MEDICINE, and use them to stay healthy.\r\n\r\nIf you're really hurt, there's a MEDICAL DROID in each spaceport who will restore your health completely.",
	57388: "Watch out! This is DARTH VADER.\r\n\r\nBeware the dark side!",
	57389: "Congratulations! You've won a battle with the Empire!\r\n\r\nTo start a new game, pull down the File menu and select NEW WORLD.",
	57390: "The Empire has defeated you... temporarily.\r\n\r\nTo start a new game, pull down the FILE menu and select NEW WORLD.",
	57391: "This EWOK is a friendly creature. It won't hurt you.",
	57360: "a map...",
	57361: "something useful...",
	57362: "the Force...",
	57363: "Spaceport",
	57364: "You've Won!",
	57365: "unknown...",
	57366: "a tool...",
	57367: "a part...",
	57368: "a valuable...",
	57369: "a key card...",
	57370: "...open! ",
	57371: "Leave Yoda Stories?",
	57372: "Sorry, there is no story saved to replay!\n Build a New World instead.",
	57373: "There is not enough memory to run\nYoda Stories.  Try closing\nany other running programs, then\nstart Yoda Stories again.",
	57374: "An unrecoverable error has occured.  Yoda Stories will close.",
	57375: "Enemy mild text.",
	2: "Yoda Stories",
	3: "This command will discard\nthe current world.\nLoad anyway?",
	4: "Yoda Stories may have difficulty\nplaying music (MIDI files) on your system.\nTo avoid the problem, music has now been\nturned OFF.  To override this setting, select\nMUSIC ON from the Options Menu.\n",
	5: "Yoda Stories could not\nopen the data file YODESK.DTA.\nCheck to see that the file exists in the\ninstalled directory, or re-install the game.",
	6: "A sharing violation occurred trying\nto open the DESKTOP.DTA data file.\nThis file must have the READ ONLY\nattribute.  Try re-installing the game\nfrom the original floppy disk to cure\nthe problem.",
	7: "The disk you tried to write to is\nfull or write-protected.  Choose\nanother drive, or remove the\nwrite-protect tab if the drive is\na floppy disk.",
	8: "Yoda Stories was unable\nto open the file you specified.\nTry another drive, or make sure\nthe disk is inserted properly if the\ndrive is a floppy disk.",
	9: "Yoda Stories was unable\nto create the file you specified.\nTry another drive or directory, or\nmake sure the disk is inserted\nproperly if the drive is a floppy\ndisk drive.",
	57344: "Yoda Stories",
	57345: "This command will discard\nthe current world.\nBuild a New World anyway?",
	57346: "Couldn't open data file!",
	57347: "Wrong version DTA File!",
	57348: "Loading Game Data...",
	57349: "Building Game World...",
	57350: "World Files (*.wld) | *.wld",
	57351: "World Files (*.wld) | *.wld",
	57352: "This file is not a Yoda Stories Saved World!",
	57353: "This command will discard\nthe current world.\nReplay anyway?",
	57354: "Yoda Stories cannot run\nin 16-color video modes. Please\nconsult your Windows documentation\non how to restart Windows in a video\nmode that can display at least 256 colors.",
	57355: "Well done, Luke! ",
	57356: "Now I can put Marcus back where he belongs...",
	57357: "...solved! ",
	57358: "requires ",
	57359: "find "
};
