import {
	parseVersion as VERS,
	parseSetupImage as STUP,
	parseSounds as SNDS,
	parseTiles as TILE,
	parseZones as ZONE,
	parsePuzzles as PUZ2,
	parseCharacters as CHAR,
	parseCharacterWeapons as CHWP,
	parseCharacterAux as CAUX,
	parseTileNames as TNAM,
	parseZaux as ZAUX,
	parseZax2 as ZAX2,
	parseZax3 as ZAX3,
	parseZax4 as ZAX4,
	parseHotspots as HTSP,
	parseActions as ACTN,
	parseZoneNames as ZNAM,
	parsePuzzleNames as PNAM,
	parseActionNames as ANAM,
	parseEndOfFile as ENDF
} from "./categories";

export default {
	VERS,
	STUP,
	SNDS,
	TILE,
	ZONE,
	PUZ2,
	CHAR,
	CHWP,
	CAUX,
	TNAM,
	ZAUX,
	ZAX2,
	ZAX3,
	ZAX4,
	HTSP,
	ACTN,
	ZNAM,
	PNAM,
	ANAM,
	ENDF
} as any;
