import * as AddHealth from "./add-health";
import * as AddItem from "./add-item";
import * as AddToCounter from "./add-to-counter";
import * as AddToPadding from "./add-to-padding";
import * as ChangeZone from "./change-zone";
import * as DisableAction from "./disable-action";
import * as DisableAllNpcs from "./disable-all-npcs";
import * as DisableHotspot from "./disable-hotspot";
import * as DisableNpc from "./disable-npc";
import * as DrawTile from "./draw-tile";
import * as DropItem from "./drop-item";
import * as EnableAllNpcs from "./enable-all-npcs";
import * as EnableHotspot from "./enable-hotspot";
import * as EnableNpc from "./enable-npc";
import * as HideHero from "./hide-hero";
import * as LoseGame from "./lose-game";
import * as MarkAsSolved from "./mark-as-solved";
import * as MoveHeroBy from "./move-hero-by";
import * as MoveTile from "./move-tile";
import * as PlaceTile from "./place-tile";
import * as PlaceTile_Alias_ from "./place-tile-alias";
import * as PlaySound from "./play-sound";
import * as Redraw from "./redraw";
import * as RemoveItem from "./remove-item";
import * as RemoveTile from "./remove-tile";
import * as RollDice from "./roll-dice";
import * as SetCounter from "./set-counter";
import * as MoveHeroTo from "./move-hero-to";
import * as SetPadding from "./set-padding";
import * as SetRandom from "./set-random";
import * as SetRectNeedsDisplay from "./set-rect-needs-display";
import * as SetTileNeedsDisplay from "./set-tile-needs-display";
import * as ShowHero from "./show-hero";
import * as SpeakHero from "./speak-hero";
import * as SpeakNpc from "./speak-npc";
import * as StopSound from "./stop-sound";
import * as Wait from "./wait";
import * as WinGame from "./win-game";

const Instructions = <{[_: string]: Function}>{};
const exportInstruction = (I: any) => Instructions[I.Opcode] = I.default;

exportInstruction(PlaceTile);
exportInstruction(RemoveTile);
exportInstruction(MoveTile);
exportInstruction(DrawTile);
exportInstruction(SpeakHero);
exportInstruction(SpeakNpc);
exportInstruction(EnableNpc);
exportInstruction(DisableNpc);
exportInstruction(EnableAllNpcs);
exportInstruction(DisableAllNpcs);
exportInstruction(SetTileNeedsDisplay);
exportInstruction(SetRectNeedsDisplay);
exportInstruction(Wait);
exportInstruction(Redraw);
exportInstruction(PlaySound);
exportInstruction(StopSound);
exportInstruction(RollDice);
exportInstruction(SetCounter);
exportInstruction(PlaceTile_Alias_);
exportInstruction(HideHero);
exportInstruction(ShowHero);
exportInstruction(MoveHeroTo);
exportInstruction(DisableAction);
exportInstruction(DisableHotspot);
exportInstruction(EnableHotspot);
exportInstruction(DropItem);
exportInstruction(AddItem);
exportInstruction(RemoveItem);
exportInstruction(ChangeZone);
exportInstruction(SetPadding);
exportInstruction(AddToPadding);
exportInstruction(SetRandom);
exportInstruction(AddHealth);
exportInstruction(AddToCounter);
exportInstruction(WinGame);
exportInstruction(LoseGame);
exportInstruction(MarkAsSolved);
exportInstruction(MoveHeroBy);

export default Instructions;

const Opcode = <{[_: string]: any}>{};
const exportOpcode = (name: string, {Opcode: code}: {Opcode: any}) => Opcode[name] = code;
exportOpcode("PlaceTile", PlaceTile);
exportOpcode("RemoveTile", RemoveTile);
exportOpcode("MoveTile", MoveTile);
exportOpcode("DrawTile", DrawTile);
exportOpcode("SpeakHero", SpeakHero);
exportOpcode("SpeakNpc", SpeakNpc);
exportOpcode("EnableNpc", EnableNpc);
exportOpcode("DisableNpc", DisableNpc);
exportOpcode("EnableAllNpcs", EnableAllNpcs);
exportOpcode("DisableAllNpcs", DisableAllNpcs);
exportOpcode("SetTileNeedsDisplay", SetTileNeedsDisplay);
exportOpcode("SetRectNeedsDisplay", SetRectNeedsDisplay);
exportOpcode("Wait", Wait);
exportOpcode("Redraw", Redraw);
exportOpcode("PlaySound", PlaySound);
exportOpcode("StopSound", StopSound);
exportOpcode("RollDice", RollDice);
exportOpcode("SetCounter", SetCounter);
exportOpcode("PlaceTile_Alias_", PlaceTile_Alias_);
exportOpcode("HideHero", HideHero);
exportOpcode("ShowHero", ShowHero);
exportOpcode("MoveHeroTo", MoveHeroTo);
exportOpcode("DisableAction", DisableAction);
exportOpcode("DisableHotspot", DisableHotspot);
exportOpcode("EnableHotspot", EnableHotspot);
exportOpcode("DropItem", DropItem);
exportOpcode("AddItem", AddItem);
exportOpcode("RemoveItem", RemoveItem);
exportOpcode("ChangeZone", ChangeZone);
exportOpcode("SetPadding", SetPadding);
exportOpcode("AddToPadding", AddToPadding);
exportOpcode("SetRandom", SetRandom);
exportOpcode("AddHealth", AddHealth);
exportOpcode("AddToCounter", AddToCounter);
exportOpcode("WinGame", WinGame);
exportOpcode("LoseGame", LoseGame);
exportOpcode("MarkAsSolved", MarkAsSolved);
exportOpcode("MoveHeroBy", MoveHeroBy);
export { Opcode };

export { PlaceTile };
export { RemoveTile };
export { MoveTile };
export { DrawTile };
export { SpeakHero };
export { SpeakNpc };
export { EnableNpc };
export { DisableNpc };
export { EnableAllNpcs };
export { DisableAllNpcs };
export { SetTileNeedsDisplay };
export { SetRectNeedsDisplay };
export { Wait };
export { Redraw };
export { PlaySound };
export { StopSound };
export { RollDice };
export { SetCounter };
export { PlaceTile_Alias_ };
export { HideHero };
export { ShowHero };
export { MoveHeroTo };
export { MoveHeroBy };
export { DisableAction };
export { DisableHotspot };
export { EnableHotspot };
export { DropItem };
export { AddItem };
export { RemoveItem };
export { ChangeZone };
export { SetPadding };
export { AddToPadding };
export { SetRandom };
export { AddHealth };
export { AddToCounter };
export { LoseGame };
export { WinGame };
export { MarkAsSolved };
