import { Opcode } from "/engine/objects/instruction";

import PlaceTile from "./place-tile";
import RemoveTile from "./remove-tile";
import MoveTile from "./move-tile";
import DrawTile from "./draw-tile";
import SpeakHero from "./speak-hero";
import SpeakNPC from "./speak-npc";
import EnableNPC from "./enable-npc";
import DisableNPC from "./disable-npc";
import EnableAllNPCs from "./enable-all-npcs";
import DisableAllNPCs from "./disable-all-npcs";
import SetTileNeedsDisplay from "./set-tile-needs-display";
import SetRectNeedsDisplay from "./set-rect-needs-display";
import Wait from "./wait";
import Redraw from "./redraw";
import PlaySound from "./play-sound";
import StopSound from "./stop-sound";
import RollDice from "./roll-dice";
import SetCounter from "./set-counter";
import PlaceTile_Alias_ from "./place-tile-alias";
import HideHero from "./hide-hero";
import ShowHero from "./show-hero";
import SetHero from "./set-hero";
import MoveHeroBy from "./move-hero-by";
import DisableAction from "./disable-action";
import DisableHotspot from "./disable-hotspot";
import EnableHotspot from "./enable-hotspot";
import DropItem from "./drop-item";
import AddItem from "./add-item";
import RemoveItem from "./remove-item";
import ChangeZone from "./change-zone";
import SetPadding from "./set-padding";
import AddToPadding from "./add-to-padding";
import SetRandom from "./set-random";
import AddHealth from "./add-health";
import AddToCounter from "./add-to-counter";
import LoseGame from "./lose-game";
import WinGame from "./win-game";
import MarkAsSolved from "./mark-as-solved";

const Instructions = {};

Instructions[Opcode.PlaceTile] = PlaceTile;
Instructions[Opcode.RemoveTile] = RemoveTile;
Instructions[Opcode.MoveTile] = MoveTile;
Instructions[Opcode.DrawTile] = DrawTile;
Instructions[Opcode.SpeakHero] = SpeakHero;
Instructions[Opcode.SpeakNPC] = SpeakNPC;
Instructions[Opcode.EnableNPC] = EnableNPC;
Instructions[Opcode.DisableNPC] = DisableNPC;
Instructions[Opcode.EnableAllNPCs] = EnableAllNPCs;
Instructions[Opcode.DisableAllNPCs] = DisableAllNPCs;
Instructions[Opcode.SetTileNeedsDisplay] = SetTileNeedsDisplay;
Instructions[Opcode.SetRectNeedsDisplay] = SetRectNeedsDisplay;
Instructions[Opcode.Wait] = Wait;
Instructions[Opcode.Redraw] = Redraw;
Instructions[Opcode.PlaySound] = PlaySound;
Instructions[Opcode.StopSound] = StopSound;
Instructions[Opcode.RollDice] = RollDice;
Instructions[Opcode.SetCounter] = SetCounter;
Instructions[Opcode.PlaceTile_Alias_] = PlaceTile_Alias_;
Instructions[Opcode.HideHero] = HideHero;
Instructions[Opcode.ShowHero] = ShowHero;
Instructions[Opcode.SetHero] = SetHero;
Instructions[Opcode.DisableAction] = DisableAction;
Instructions[Opcode.DisableHotspot] = DisableHotspot;
Instructions[Opcode.EnableHotspot] = EnableHotspot;
Instructions[Opcode.DropItem] = DropItem;
Instructions[Opcode.AddItem] = AddItem;
Instructions[Opcode.RemoveItem] = RemoveItem;
Instructions[Opcode.ChangeZone] = ChangeZone;
Instructions[Opcode.SetPadding] = SetPadding;
Instructions[Opcode.AddToPadding] = AddToPadding;
Instructions[Opcode.SetRandom] = SetRandom;
Instructions[Opcode.AddHealth] = AddHealth;
Instructions[Opcode.AddToCounter] = AddToCounter;
Instructions[Opcode.WinGame] = WinGame;
Instructions[Opcode.LoseGame] = LoseGame;
Instructions[Opcode.MarkAsSolved] = MarkAsSolved;
Instructions[Opcode.MoveHeroBy] = MoveHeroBy;

export default Instructions;
