[book]
authors = ["Christoph Leimbrock"]
language = "en"
multilingual = false
src = "src"
title = "WebFun"

[build]
build-dir = "../build/docs"
create-missing = false

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

# [output.linkcheck]

[output.html]
git-repository-url = "https://github.com/cyco/webfun/"
git-branch = "master"
additional-css = ["open-in.css"]
