[book]
authors = ["Christoph Leimbrock"]
language = "en"
multilingual = false
src = "src"
title = "WebFun"

[build]
build-dir = "../build/docs"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

# [output.linkcheck]

[output.html]
git-repository-url = "https://github.com/cyco/webfun/docs/"
additional-css = ["open-in.css"]
